---
- name: Check OS version and family
  fail:
    msg: "This role can only be run against RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: (ansible_distribution != "RedHat" or ansible_distribution_major_version != "7")
  tags:
    - always

- name: Check ansible version
  fail:
    msg: You must use ansible 2.7 or greater
  when: ansible_version.full is version('2.7', '<')
  tags:
    - always

- include: prelim.yml
  become: yes
  tags:
    - always

- include: section1.yml
  become: yes
  when: rhel7cis_section1

- include: section2.yml
  become: yes
  when: rhel7cis_section2

- include: section3.yml
  become: yes
  when: rhel7cis_section3

- include: section4.yml
  become: yes
  when: rhel7cis_section4

- include: section5.yml
  become: yes
  when: rhel7cis_section5

- include: section6.yml
  become: yes
  when: rhel7cis_section6

- include: section7.yml
  become: yes
  when: rhel7cis_section7

- include: post.yml
  become: yes
  tags:
    - always
