---
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: no
  check_mode: no

- name: "PRELIM | Gather accounts with empty password fields"
  shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  register: empty_password_accounts
  changed_when: no
  check_mode: no

- name: "PRELIM | Gather UID 0 accounts other than root"
  shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  register: uid_zero_accounts_except_root
  changed_when: no
  check_mode: no

- name: "PRELIM | Section 4.1 | Install System Accounting (auditd)"
  yum:
    name: audit

- name: "PRELIM | Section 5.1 | Install cron"
  yum:
    name: cronie

- name: "PRELIM | Check if prelink package is installed"
  command: rpm -q prelink
  register: prelink_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
    - skip_ansible_lint

- name: "PRELIM | Check if server is subscribed"
  shell: "subscription-manager status | grep -i 'overall status' | awk -F ': ' '{ print $2}'"
  register: subscription_status
  changed_when: no
  failed_when: no

- name: "PRELIM | Check for xinetd service"
  systemd:
    name: xinetd
  register: xinetd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for avahi-daemon service"
  systemd:
    name: avahi-daemon
  register: avahi_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for cups service"
  systemd:
    name: cups
  register: cups_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for dhcpd service"
  systemd:
    name: dhcpd
  register: dhcpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for slapd service"
  systemd:
    name: slapd
  register: slapd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for nfs service"
  systemd:
    name: nfs
  register: nfs_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rpcbind service"
  systemd:
    name: rpcbind
  register: rpcbind_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for named service"
  systemd:
    name: named
  register: named_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for vsftpd service"
  systemd:
    name: vsftpd
  register: vsftpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for httpd service"
  systemd:
    name: httpd
  register: httpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for dovecot service"
  systemd:
    name: dovecot
  register: dovecot_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for smb service"
  systemd:
    name: smb
  register: smb_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for squid service"
  systemd:
    name: squid
  register: squid_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for snmpd service"
  systemd:
    name: snmpd
  register: snmpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for ypserv service"
  systemd:
    name: ypserv
  register: ypserv_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rsh.socket service"
  systemd:
    name: rsh.socket
  register: rsh_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rlogin.socket service"
  systemd:
    name: rlogin.socket
  register: rlogin_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rexec.socket service"
  systemd:
    name: rexec.socket
  register: rexec_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for telnet service"
  systemd:
    name: telnet
  register: telnet_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for tftp service"
  systemd:
    name: tftp
  register: tftp_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rhnsd service"
  systemd:
    name: rhnsd
  register: rhnsd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rsyncd service"
  systemd:
    name: rsyncd
  register: rsyncd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for ntalk service"
  systemd:
    name: ntalk
  register: ntalk_service_status
  changed_when: no
  check_mode: no
