---
- name: "SCORED | 3.1.1 | Ensure IP forwarding is disabled\n
         SCORED | 3.1.2 | Ensure packet redirect sending is disabled\n
         SCORED | 3.2.1 | Ensure source routed packets are not accepted\n
         SCORED | 3.2.2 | Ensure ICMP redirects are not accepted\n
         SCORED | 3.2.3 | Ensure secure ICMP redirects are not accepted\n
         SCORED | 3.2.4 | Ensure suspicious packets are logged\n
         SCORED | 3.2.5 | Ensure broadcast ICMP requests are ignored\n
         SCORED | 3.2.6 | Ensure bogus ICMP responses are ignored\n
         SCORED | 3.2.7 | Ensure Reverse Path Filtering is enabled\n
         SCORED | 3.2.8 | Ensure TCP SYN Cookies is enabled\n"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  loop:
    - { name: net.ipv4.ip_forward, value: 0 }
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    - { name: net.ipv4.conf.default.send_redirects, value: 0 }
    - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
    - { name: net.ipv4.conf.all.log_martians, value: 1 }
    - { name: net.ipv4.conf.default.log_martians, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    - { name: net.ipv4.tcp_syncookies, value: 1 }
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel7cis_rule_3_1_1
    - rhel7cis_rule_3_1_2
    - rhel7cis_rule_3_2_1
    - rhel7cis_rule_3_2_2
    - rhel7cis_rule_3_2_3
    - rhel7cis_rule_3_2_4
    - rhel7cis_rule_3_2_5
    - rhel7cis_rule_3_2_6
    - rhel7cis_rule_3_2_7
    - rhel7cis_rule_3_2_8
  tags:
    - rule_3.1.1
    - rule_3.1.2
    - rule_3.2.1
    - rule_3.2.2
    - rule_3.2.3
    - rule_3.2.4
    - rule_3.2.5
    - rule_3.2.6
    - rule_3.2.7
    - rule_3.2.8

- block:
    - name: "NOTSCORED | 3.3.1 | Ensure IPv6 router advertisements are not accepted"
      stat:
        path: /proc/sys/net/ipv6/conf/default/accept_ra
      register: accept_ra

    - name: "NOTSCORED | 3.3.1 | Ensure IPv6 router advertisements are not accepted"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        reload: yes
      loop:
        - { name: net.ipv6.conf.all.accept_ra, value: 0 }
        - { name: net.ipv6.conf.default.accept_ra, value: 0 }
      notify:
        - sysctl flush ipv6 route table
      when:
        - accept_ra.stat.exists == True
  when:
    - rhel7cis_rule_3_3_1
  tags:
    - rule_3.3.1

- block:
    - name: "NOTSCORED | 3.3.2 | Ensure IPv6 redirects are not accepted"
      stat:
        path: /proc/sys/net/ipv6/conf/default/accept_redirects
      register: accept_redirects

    - name: "NOTSCORED | 3.3.2 | Ensure IPv6 redirects are not accepted"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        reload: yes
      loop:
        - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
        - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
      notify:
        - sysctl flush ipv6 route table
      when:
        - accept_redirects.stat.exists == True
  when:
    - rhel7cis_rule_3_3_2
  tags:
    - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | Ensure IPv6 is disabled"
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX\s*\=\s*(?!.*ipv6.disable_ipv6)\"[^\"]+)(\".*)'
    line: '\1 ipv6.disable_ipv6=1\2'
    backup: yes
  notify: generate new grub config
  when:
    - rhel7cis_rule_3_3_3
  tags:
    - rule_3.3.3

- name: "SCORED | 3.4.1 | Ensure TCP Wrappers is installed"
  yum:
    name: tcp_wrappers
  when:
    - rhel7cis_rule_3_4_1
  tags:
    - rule_3.4.1

- name: "SCORED | 3.4.2 | Ensure /etc/hosts.allow is configured\n
         SCORED | 3.4.3 | Ensure /etc/hosts.deny is configured\n
         SCORED | 3.4.4 | Ensure permissions on /etc/hosts.allow are configured\n
         SCORED | 3.4.5 | Ensure permissions on /etc/hosts.deny are configured"
  copy:
    dest: "{{ item }}"
    content: "ALL: ALL"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop:
    - /etc/hosts.allow
    - /etc/hosts.deny
  when:
    - rhel7cis_rule_3_4_2
    - rhel7cis_rule_3_4_3
    - rhel7cis_rule_3_4_4
    - rhel7cis_rule_3_4_5
  tags:
    - rule_3.4.2
    - rule_3.4.3
    - rule_3.4.4
    - rule_3.4.5

- name: "NOTSCORED | 3.5.1 | Ensure DCCP is disabled\n
         NOTSCORED | 3.5.2 | Ensure SCTP is disabled\n
         NOTSCORED | 3.5.3 | Ensure RDS is disabled\n
         NOTSCORED | 3.5.4 | Ensure TIPC is disabled"
  template:
    src: etc/modprobe.d/CIS.conf
    dest: /etc/modprobe.d/CIS.conf
    owner: root
    groups: root
    mode: 0644
    backup: yes
  when:
    - rhel7cis_rule_3_5_1
    - rhel7cis_rule_3_5_2
    - rhel7cis_rule_3_5_3
    - rhel7cis_rule_3_5_4
  tags:
    - rule_3.5.1
    - rule_3.5.2
    - rule_3.5.3
    - rule_3.5.4

- block:
    - name: "SCORED | 3.6.1 | Ensure firewalld is installed"
      yum:
        name: iptables

    - name: "SCORED | 3.6.1 | Ensure firewalld is started"
      systemd:
        name: firewalld
        state: started
        enabled: yes
  when:
    - rhel7cis_rule_3_6_1
  tags:
    - rule_3.6.1

- name: "NOTSCORED | 3.7 | Ensure wireless interfaces are disabled"
  debug:
    msg: "There is no wireless connection on our servers"
  tags:
    - rule_3.7
