---
- block:
    - name: "SCORED | 2.1.1 | Ensure chargen services are not enabled | chargen-dgram"
      stat:
        path: /etc/xinetd.d/chargen-dgram
      register: chargen_dgram_service

    - name: "SCORED | 2.1.1 | Ensure chargen services are not enabled | chargen-dgram"
      systemd:
        name: chargen-dgram
        state: stopped
        enabled: no
      notify: restart xinetd
      when: chargen_dgram_service.stat.exists

    - name: "SCORED | 2.1.1 | Ensure chargen services are not enabled | chargen-stream"
      stat:
        path: /etc/xinetd.d/chargen-stream
      register: chargen_stream_service

    - name: "SCORED | 2.1.1 | Ensure chargen services are not enabled | chargen-stream"
      systemd:
        name: chargen-stream
        state: stopped
        enabled: no
      notify: restart xinetd
      when: chargen_stream_service.stat.exists
  when:
    - rhel7cis_rule_2_1_1
  tags:
    - rule_2.1.1

- block:
    - name: "SCORED | 2.1.2 | Ensure daytime services are not enabled | daytime-dgram"
      stat:
        path: /etc/xinetd.d/daytime-dgram
      register: daytime_dgram_service

    - name: "SCORED | 2.1.2 | Ensure daytime services are not enabled | daytime-dgram"
      systemd:
        name: daytime-dgram
        state: stopped
        enabled: no
      notify: restart xinetd
      when: daytime_dgram_service.stat.exists

    - name: "SCORED | 2.1.2 | Ensure daytime services are not enabled | daytime-stream"
      stat:
        path: /etc/xinetd.d/daytime-stream
      register: daytime_stream_service

    - name: "SCORED | 2.1.2 | Ensure daytime services are not enabled | daytime-stream"
      systemd:
        name: daytime-stream
        state: stopped
        enabled: no
      notify: restart xinetd
      when: daytime_stream_service.stat.exists
  when:
    - rhel7cis_rule_2_1_2
  tags:
    - rule_2.1.2

- block:
    - name: "SCORED | 2.1.3 | Ensure discard services are not enabled | discard-dgram"
      stat:
        path: /etc/xinetd.d/discard-dgram
      register: discard_dgram_service

    - name: "SCORED | 2.1.3 | Ensure discard services are not enabled | discard-dgram"
      systemd:
        name: discard-dgram
        state: stopped
        enabled: no
      notify: restart xinetd
      when: discard_dgram_service.stat.exists

    - name: "SCORED | 2.1.3 | Ensure discard services are not enabled | discard-stream"
      stat:
        path: /etc/xinetd.d/discard-stream
      register: discard_stream_service

    - name: "SCORED | 2.1.3 | Ensure discard services are not enabled | discard-stream"
      systemd:
        name: discard-stream
        state: stopped
        enabled: no
      notify: restart xinetd
      when: discard_stream_service.stat.exists
  when:
    - rhel7cis_rule_2_1_3
  tags:
    - rule_2.1.3

- block:
    - name: "SCORED | 2.1.4 | Ensure echo services are not enabled | echo-dgram"
      stat:
        path: /etc/xinetd.d/echo-dgram
      register: echo_dgram_service

    - name: "SCORED | 2.1.4 | Ensure echo services are not enabled | echo-dgram"
      systemd:
        name: echo-dgram
        state: stopped
        enabled: no
      notify: restart xinetd
      when: echo_dgram_service.stat.exists

    - name: "SCORED | 2.1.4 | Ensure echo services are not enabled | echo-stream"
      stat:
        path: /etc/xinetd.d/echo-stream
      register: echo_stream_service

    - name: "SCORED | 2.1.4 | Ensure echo services are not enabled | echo-stream"
      systemd:
        name: echo-stream
        state: stopped
        enabled: no
      notify: restart xinetd
      when: echo_stream_service.stat.exists
  when:
    - rhel7cis_rule_2_1_4
  tags:
    - rule_2.1.4

- block:
    - name: "SCORED | 2.1.5 | Ensure time services are not enabled | time-dgram"
      stat:
        path: /etc/xinetd.d/time-dgram
      register: time_dgram_service

    - name: "SCORED | 2.1.5 | Ensure time services are not enabled | time-dgram"
      systemd:
        name: time-dgram
        state: stopped
        enabled: no
      notify: restart xinetd
      when: time_dgram_service.stat.exists

    - name: "SCORED | 2.1.5 | Ensure time services are not enabled | time-stream"
      stat:
        path: /etc/xinetd.d/time-stream
      register: time_stream_service

    - name: "SCORED | 2.1.5 | Ensure time services are not enabled | time-stream"
      systemd:
        name: time-stream
        state: stopped
        enabled: no
      notify: restart xinetd
      when: time_stream_service.stat.exists
  when:
    - rhel7cis_rule_2_1_5
  tags:
    - rule_2.1.5

- name: "SCORED | 2.1.6 | Ensure tftp server is not enabled"
  systemd:
    name: tftp
    state: stopped
    enabled: no
  when:
    - tftp_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_1_6
  tags:
    - rule_2.1.6

- name: "SCORED | 2.1.7 | Ensure xinetd is not enabled"
  systemd:
    name: xinetd
    state: stopped
    enabled: no
  when:
    - xinetd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_1_7
  tags:
    - rule_2.1.7

- block:
    - name: "NOTSCORED | 2.2.1.1 | Ensure time synchronization is in use - service install"
      yum:
        name: chrony

    - name: "NOTSCORED | 2.2.1.1 | Ensure time synchronization is in use - service start"
      systemd:
        name: chronyd
        state: started
        enabled: yes

    - name: "NOTSCORED | 2.2.1.1 | Ensure time synchronization is in use - service stop ntpd"
      systemd:
        name: ntpd
        state: stopped
        enabled: no
  when:
    - rhel7cis_rule_2_2_1_1
  tags:
    - rule_2.2.1.1

- name: "SCORED | 2.2.1.2 | Ensure ntp is configured | modify /etc/ntp.conf"
  debug:
    msg: "Not needed as only chrony is used"
  when:
    - rhel7cis_rule_2_2_1_2
  tags:
    - rule_2.2.1.2

- block:
    - name: "SCORED | 2.2.1.3 | Ensure chrony is configured"
      template:
        src: etc/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644

    - name: "SCORED | 2.2.1.3 | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
      lineinfile:
        dest: /etc/sysconfig/chronyd
        regexp: "^OPTIONS"
        line: "OPTIONS=\"-u chrony\""
        state: present
        create: yes
  when:
    - rhel7cis_rule_2_2_1_3
  tags:
    - rule_2.2.1.3

- name: "SCORED | 2.2.2 | Ensure X Window System is not installed"
  yum:
    name: xorg-x11*
    state: absent
  when:
    - rhel7cis_rule_2_2_2
  tags:
    - rule_2.2.2

- name: "SCORED | 2.2.3 | Ensure Avahi Server is not enabled"
  systemd:
    name: avahi-daemon
    state: stopped
    enabled: no
  failed_when: no
  when:
    - avahi_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_3
  tags:
    - rule_2.2.3

- name: "SCORED | 2.2.4 | Ensure CUPS is not enabled"
  systemd:
    name: cups
    state: stopped
    enabled: no
  when:
    - cups_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_4
  tags:
    - rule_2.2.4

- name: "SCORED | 2.2.5 | Ensure DHCP Server is not enabled"
  systemd:
    name: dhcpd
    state: stopped
    enabled: no
  when:
    - dhcpd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_5
  tags:
    - rule_2.2.5

- name: "SCORED | 2.2.6 | Ensure LDAP server is not enabled"
  systemd:
    name: slapd
    state: stopped
    enabled: no
  when:
    - slapd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_6
  tags:
    - rule_2.2.6

- block:
    - name: "SCORED | 2.2.7 | Ensure NFS and RPC are not enabled"
      systemd:
        name: nfs
        state: stopped
        enabled: no
      when:
        - nfs_service_status.status.LoadState == "loaded"

    - name: "SCORED | 2.2.7 | Ensure RPC is not enabled"
      systemd:
        name: rpcbind
        state: stopped
        enabled: no
      when:
        - rpcbind_service_status.status.LoadState == "loaded"
  when:
    - rhel7cis_rule_2_2_7
  tags:
    - rule_2.2.7

- name: "SCORED | 2.2.8 | Ensure DNS Server is not enabled"
  systemd:
    name: named
    state: stopped
    enabled: no
  when:
    - named_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_8
  tags:
    - rule_2.2.8

- name: "SCORED | 2.2.9 | Ensure FTP Server is not enabled"
  systemd:
    name: vsftpd
    state: stopped
    enabled: no
  when:
    - vsftpd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_9
  tags:
    - rule_2.2.9

- name: "SCORED | 2.2.10 | Ensure HTTP server is not enabled"
  systemd:
    name: httpd
    state: stopped
    enabled: no
  when:
    - httpd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_10
  tags:
    - rule_2.2.10

- name: "SCORED | 2.2.11 | Ensure IMAP and POP3 server is not enabled"
  systemd:
    name: dovecot
    state: stopped
    enabled: no
  when:
    - dovecot_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_11
  tags:
    - rule_2.2.11

- name: "SCORED | 2.2.12 | Ensure Samba is not enabled"
  systemd:
    name: smb
    state: stopped
    enabled: no
  when:
    - smb_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_12
  tags:
    - rule_2.2.12

- name: "SCORED | 2.2.13 | Ensure HTTP Proxy Server is not enabled"
  systemd:
    name: squid
    state: stopped
    enabled: no
  when:
    - squid_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_13
  tags:
    - rule_2.2.13

- name: "SCORED | 2.2.14 | Ensure SNMP Server is not enabled"
  systemd:
    name: snmpd
    state: stopped
    enabled: no
  when:
    - snmpd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_14
  tags:
    - rule_2.2.14

- name: "SCORED | 2.2.15 | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = loopback-only"
    backup: yes
  notify: restart postfix
  when:
    - rhel7cis_rule_2_2_15
  tags:
    - rule_2.2.15

- name: "SCORED | 2.2.16 | Ensure NIS Server is not enabled"
  systemd:
    name: ypserv
    state: stopped
    enabled: no
  when:
    - ypserv_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_16
  tags:
    - rule_2.2.16

- name: "SCORED | 2.2.17 | Ensure rsh server is not enabled | rsh"
  systemd:
    name: rsh.socket
    state: stopped
    enabled: no
  when:
    - rsh_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_17
  tags:
    - rule_2.2.17

- name: "SCORED | 2.2.17 | Ensure rsh server is not enabled | rlogin"
  systemd:
    name: rlogin.socket
    state: stopped
    enabled: no
  when:
    - rlogin_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_17
  tags:
    - rule_2.2.17

- name: "SCORED | 2.2.17 | Ensure rsh server is not enabled | rexec"
  systemd:
    name: rexec.socket
    state: stopped
    enabled: no
  when:
    - rexec_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_17
  tags:
    - rule_2.2.17

- name: "SCORED | 2.2.18 | Ensure telnet server is not enabled"
  systemd:
    name: telnet
    state: stopped
    enabled: no
  when:
    - telnet_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_18
  tags:
    - rule_2.2.18

- name: "SCORED | 2.2.19 | Ensure tftp server is not enabled"
  systemd:
    name: tftp
    state: stopped
    enabled: no
  when:
    - tftp_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_19
  tags:
    - rule_2.2.19

- name: "SCORED | 2.2.20 | Ensure rsync service is not enabled "
  systemd:
    name: rsyncd
    state: stopped
    enabled: no
  when:
    - rsyncd_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_20
  tags:
    - rule_2.2.20

- name: "SCORED | 2.2.21 | Ensure talk server is not enabled"
  systemd:
    name: ntalk
    state: stopped
    enabled: no
  when:
    - ntalk_service_status.status.LoadState == "loaded"
    - rhel7cis_rule_2_2_21
  tags:
    - rule_2.2.21

- name: "SCORED | 2.3.1 | Ensure NIS Client is not installed"
  yum:
    name: ypbind
    state: absent
  when:
    - rhel7cis_rule_2_3_1
  tags:
    - rule_2.3.1

- name: "SCORED | 2.3.2 | Ensure rsh client is not installed"
  yum:
    name: rsh
    state: absent
  when:
    - rhel7cis_rule_2_3_2
  tags:
    - rule_2.3.2

- name: "SCORED | 2.3.3 | Ensure talk client is not installed"
  yum:
    name: talk
    state: absent
  when:
    - rhel7cis_rule_2_3_3
  tags:
    - rule_2.3.3

- name: "SCORED | 2.3.4 | Ensure telnet client is not installed"
  yum:
    name: telnet
    state: absent
  when:
    - rhel7cis_rule_2_3_4
  tags:
    - rule_2.3.4

- name: "SCORED | 2.3.5 | Ensure LDAP client is not installed"
  yum:
    name: openldap-clients
    state: absent
  when:
    - rhel7cis_rule_2_3_5
  tags:
    - rule_2.3.5
