---
- block:
    - name: "SCORED | 1.1.1.1 | Ensure mounting of cramfs filesystems is disabled\n
             SCORED | 1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled\n
             SCORED | 1.1.1.3 | Ensure mounting of jffs2 filesystems is disabled\n
             SCORED | 1.1.1.4 | Ensure mounting of hfs filesystems is disabled\n
             SCORED | 1.1.1.5 | Ensure mounting of hfsplus filesystems is disabled\n
             SCORED | 1.1.1.6 | Ensure mounting of squashfs filesystems is disabled\n
             SCORED | 1.1.1.7 | Ensure mounting of udf filesystems is disabled\n
             SCORED | 1.1.1.8 | Ensure mounting of FAT filesystems is disabled"
      template:
        src: etc/modprobe.d/CIS.conf
        dest: /etc/modprobe.d/CIS.conf
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: "SCORED | 1.1.1.1 | Disable cramfs module\n
             SCORED | 1.1.1.2 | Disable freevxfs module\n
             SCORED | 1.1.1.3 | Disable jffs2 module\n
             SCORED | 1.1.1.4 | Disable hfs module\n
             SCORED | 1.1.1.5 | Disable hfsplus module\n
             SCORED | 1.1.1.6 | Disable squashfs module\n
             SCORED | 1.1.1.7 | Disable udf module\n
             SCORED | 1.1.1.8 | Disable FAT module"
      modprobe:
        name: "{{ item }}"
        state: absent
      loop:
        - cramfs
        - freevxfs
        - jffs2
        - hfs
        - hfsplus
        - squashfs
        - udf
        - vfat
  when:
    - rhel7cis_rule_1_1_1_1
    - rhel7cis_rule_1_1_1_2
    - rhel7cis_rule_1_1_1_3
    - rhel7cis_rule_1_1_1_4
    - rhel7cis_rule_1_1_1_5
    - rhel7cis_rule_1_1_1_6
    - rhel7cis_rule_1_1_1_7
    - rhel7cis_rule_1_1_1_8
  tags:
    - rule_1.1.1.1
    - rule_1.1.1.2
    - rule_1.1.1.3
    - rule_1.1.1.4
    - rule_1.1.1.5
    - rule_1.1.1.6
    - rule_1.1.1.7
    - rule_1.1.1.8

- block:
    - name: "SCORED | 1.1.2 | Ensure separate partition exists for /tmp\n
             SCORED | 1.1.3 | Ensure nodev option set on /tmp partition\n
             SCORED | 1.1.4 | Ensure nosuid option set on /tmp partition\n
             SCORED | 1.1.5 | Ensure noexec option set on /tmp partition\n"
      template:
        src: etc/systemd/system/tmp.mount
        dest: /etc/systemd/system/tmp.mount
        owner: root
        group: root
        mode: 0644
      notify:
        - reload tmp.mount

    - name: "SCORED | 1.1.2 | Ensure separate partition exists for /tmp\n
             SCORED | 1.1.3 | Ensure nodev option set on /tmp partition\n
             SCORED | 1.1.4 | Ensure nosuid option set on /tmp partition\n
             SCORED | 1.1.5 | Ensure noexec option set on /tmp partition\n"
      systemd:
        name: tmp.mount
        daemon_reload: yes
        enabled: yes
        masked: no
        state: started
  when:
    - rhel7cis_rule_1_1_2
    - rhel7cis_rule_1_1_3
    - rhel7cis_rule_1_1_4
    - rhel7cis_rule_1_1_5
  tags:
    - rule_1.1.2
    - rule_1.1.3
    - rule_1.1.4
    - rule_1.1.5

- name: "SCORED | 1.1.6 | Ensure separate partition exists for /var"
  shell: mount | grep "on /var "
  register: var_mounted
  changed_when: no
  failed_when: var_mounted == ""
  when:
    - rhel7cis_rule_1_1_6
  tags:
    - rule_1.1.6
    - skip_ansible_lint

- name: "SCORED | 1.1.7 | Ensure separate partition exists for /var/tmp"
  shell: mount | grep "on /var/tmp "
  register: var_tmp_mounted
  changed_when: no
  failed_when: var_tmp_mounted == ""
  when:
    - rhel7cis_rule_1_1_7
  tags:
    - rule_1.1.7
    - skip_ansible_lint

- name: "SCORED | 1.1.8  | Ensure nodev option set on /var/tmp partition\n
         SCORED | 1.1.9  | Ensure nosuid option set on /var/tmp partition\n
         SCORED | 1.1.10 | Ensure noexec option set on /var/tmp partition"
  mount:
    name: "/var/tmp"
    src: "/tmp"
    fstype: none
    opts: "nodev,nosuid,noexec,bind"
    state: mounted
  when:
    - rhel7cis_rule_1_1_8
    - rhel7cis_rule_1_1_9
    - rhel7cis_rule_1_1_10
  tags:
    - rule_1.1.8
    - rule_1.1.9
    - rule_1.1.10

- name: "SCORED | 1.1.11 | Ensure separate partition exists for /var/log"
  shell: mount | grep "on /var/log "
  register: var_log_mounted
  changed_when: no
  failed_when: var_log_mounted == ""
  when:
    - rhel7cis_rule_1_1_11
  tags:
    - rule_1.1.11
    - skip_ansible_lint

- name: "SCORED | 1.1.12 | Ensure separate partition exists for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: var_log_audit_mounted
  changed_when: no
  failed_when: var_log_audit_mounted == ""
  when:
    - rhel7cis_rule_1_1_12
  tags:
    - rule_1.1.12
    - skip_ansible_lint

- name: "SCORED | 1.1.13 | Ensure separate partition exists for /home"
  shell: mount | grep "on /home"
  register: home_mounted
  changed_when: no
  failed_when: home_mounted == ""
  when:
    - rhel7cis_rule_1_1_13
  tags:
    - rule_1.1.13
    - skip_ansible_lint

- name: "SCORED | 1.1.14 | Ensure nodev option set on /home partition"
  mount:
    name: "/home"
    src: "{{ item.device }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    opts: "nodev"
  when:
    - rhel7cis_rule_1_1_14
    - item.mount == "/home"
  loop: "{{ ansible_mounts }}"
  tags:
    - rule_1.1.14

- name: "SCORED | 1.1.15 | Ensure nodev option set on /dev/shm partition\n
         SCORED | 1.1.16 | Ensure nosuid option set on /dev/shm partition\n
         SCORED | 1.1.17 | Ensure noexec option set on /dev/shm partition"
  mount:
    name: /dev/shm
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: "nodev,nosuid,noexec"
  when:
    - rhel7cis_rule_1_1_15
    - rhel7cis_rule_1_1_16
    - rhel7cis_rule_1_1_17
  tags:
    - rule_1.1.15
    - rule_1.1.16
    - rule_1.1.17

- name: "NOTSCORED | 1.1.18 | Ensure nodev option set on removable media partitions\n
         NOTSCORED | 1.1.19 | Ensure nosuid option set on removable media partitions\n
         NOTSCORED | 1.1.20 | Ensure noexec option set on removable media partitions"
  debug:
    msg: "Not needed as no removable media is used"
  when:
    - rhel7cis_rule_1_1_18
    - rhel7cis_rule_1_1_19
    - rhel7cis_rule_1_1_20
  tags:
    - rule_1.1.18
    - rule_1.1.19
    - rule_1.1.20

- name: "SCORED | 1.1.21 | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: no
  ignore_errors: yes
  when:
    - rhel7cis_rule_1_1_21
  tags:
    - rule_1.1.21

- name: "SCORED | 1.1.22 | Disable Automounting"
  systemd:
    name: autofs
    enabled: no
  when:
    - rhel7cis_rule_1_1_22
  tags:
    - rule_1.1.22

- name: "NOTSCORED | 1.2.1 | Ensure package manager repositories are configured"
  debug:
    msg: "Check if subscription-manager has a current state"
  failed_when: subscription_status.stdout != "Current" or subscription_status.stderr != ""
  when:
    - rhel7cis_rule_1_2_1
  tags:
    - rule_1.2.1

- name: "SCORED | 1.2.2 | Ensure gpgcheck is globally activated"
  replace:
    name: "{{ item }}"
    regexp: "^gpgcheck=0"
    replace: "gpgcheck=1"
    backup: yes
  loop:
    - /etc/yum.conf
    - /etc/yum.repos.d/redhat.repo
  when:
    - rhel7cis_rule_1_2_2
  tags:
    - rule_1.2.2

- name: "NOTSCORED | 1.2.3 | Ensure GPG keys are configured"
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
  when:
    - rhel7cis_rule_1_2_3
  tags:
    - rule_1.2.3

- name: "NOTSCORED | 1.2.4 | Ensure Red Hat Network or Subscription Manager connection is configured"
  debug:
    msg: "Check if subscription-manager has a current state"
  failed_when: subscription_status.stdout != "Current" or subscription_status.stderr != ""
  when:
    - rhel7cis_rule_1_2_4
  tags:
    - rule_1.2.4

- name: "NOTSCORED | 1.2.5 | Disable the rhnsd Daemon"
  systemd:
    name: rhnsd
    state: stopped
    enabled: false
  when:
    - rhel7cis_rule_1_2_5
    - rhnsd_service_status.status.LoadState == "loaded"
  tags:
    - rule_1.2.5

- block:
    - name: "SCORED | 1.3.1 | Ensure AIDE is installed"
      yum:
        name: aide
        state: present

    - name: "SCORED | 1.3.1 | Ensure AIDE is installed"
      command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
      args:
        creates: /var/lib/aide/aide.db.gz
      changed_when: no
      failed_when: no
      async: 45
      poll: 0
  when:
    - rhel7cis_rule_1_3_1
  tags:
    - rule_1.3.1

- name: "SCORED | 1.3.2 | Ensure filesystem integrity is regularly checked"
  cron:
    name: Run AIDE integrity check
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/aide --check"
  when:
    - rhel7cis_rule_1_3_2
  tags:
    - rule_1.3.2

- name: "SCORED | 1.4.1 | Ensure permissions on bootloader config are configured"
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: 0600
  when:
    - rhel7cis_rule_1_4_1
  tags:
    - rule_1.4.1

- block:
    - name: "SCORED | 1.4.2 | Ensure bootloader password is set"
      grub_crypt:
        password: "{{ rhel7cis_bootloader_password }}"
        salt: MLKJi!I88828nnsdfhhqsnrS
      register: grub_pass

    - name: "SCORED | 1.4.2 | Ensure bootloader password is set"
      copy:
        dest: /boot/grub2/user.cfg
        content: "GRUB2_PASSWORD={{ grub_pass.passhash }}"
        owner: root
        group: root
        mode: 0600
      notify: generate new grub config
  when:
    - rhel7cis_set_boot_pass
    - rhel7cis_rule_1_4_2
  tags:
    - rule_1.4.2

- name: "NOTSCORED | 1.4.3 | Ensure authentication required for single user mode"
  lineinfile:
    dest: "{{ item }}"
    regexp: 'ExecStart='
    line: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
    backup: yes
  loop:
  - /usr/lib/systemd/system/emergency.service
  - /usr/lib/systemd/system/rescue.service
  when:
    - rhel7cis_rule_1_4_3
  tags:
    - rule_1.4.3

- block:
    - name: "SCORED | 1.5.1 | Ensure core dumps are restricted"
      lineinfile:
        dest: /etc/security/limits.conf
        regexp: '^#?\\*.*core'
        line: '*                hard    core            0'
        insertbefore: '^# End of file'
        backup: yes

    - name: "SCORED | 1.5.1 | Ensure core dumps are restricted"
      sysctl:
        name: fs.suid_dumpable
        value: 0
        sysctl_set: yes
  when:
    - rhel7cis_rule_1_5_1
  tags:
    - rule_1.5.1

- name: "NOTSCORED | 1.5.2 | Ensure XD/NX support is enabled"
  shell: "dmesg|grep -E 'NX ' | awk -F ': ' '{ print $2}'"
  register: xd_support
  changed_when: no
  failed_when: xd_support.stdout != "active" or xd_support.stderr != ""
  when:
    - rhel7cis_rule_1_5_2
  tags:
    - rule_1.5.2

- name: "SCORED | 1.5.3 | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
    name: kernel.randomize_va_space
    value: 2
    sysctl_set: yes
  when:
    - rhel7cis_rule_1_5_3
  tags:
    - rule_1.5.3

- block:
    - name: "SCORED | 1.5.4 | Ensure prelink is disabled"
      command: prelink -ua

    - name: "SCORED | 1.5.4 | Ensure prelink is not installed"
      yum:
        name: prelink
        state: absent
  when:
    - prelink_installed.rc == 0
    - rhel7cis_rule_1_5_4
  tags:
    - rule_1.5.4

- name: "SCORED | 1.6.1.1 | Ensure SELinux is not disabled in bootloader configuration"
  replace:
    dest: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
  register: selinux_grub_patch
  notify: generate new grub config
  when:
    - rhel7cis_rule_1_6_1_1
  tags:
    - rule_1.6.1.1

- name: "SCORED | 1.6.1.2 | Ensure the SELinux state is enforcing\n
         SCORED | 1.6.1.3 | Ensure SELinux policy is configured"
  selinux:
    conf: /etc/selinux/config
    policy: targeted
    state: enforcing
  when:
    - rhel7cis_rule_1_6_1_2
    - rhel7cis_rule_1_6_1_3
  tags:
    - rule_1.6.1.2
    - rule_1.6.1.3

- name: "SCORED | 1.6.1.4 | Ensure SETroubleshoot is not installed"
  yum:
    name: setroubleshoot
    state: absent
  when:
    - rhel7cis_rule_1_6_1_4
  tags:
    - rule_1.6.1.4

- name: "SCORED | 1.6.1.5 | Ensure the MCS Translation Service (mcstrans) is not installed"
  yum:
    name: mcstrans
    state: absent
  when:
    - rhel7cis_rule_1_6_1_5
  tags:
    - rule_1.6.1.5

- name: "SCORED | 1.6.1.6 | Ensure no unconfined daemons exist"
  shell: "ps -eZ | egrep 'initrc' | egrep -vw 'tr|ps|egrep|bash|awk|pbx_exchange|vnetd|bpcd|nbdisco|ora_|pbx_|oracle_|tnslsnr|swp' | tr ':' ' ' | awk '{ print $NF }'"
  changed_when: no
  ignore_errors: yes
  when:
    - rhel7cis_rule_1_6_1_6
  tags:
    - rule_1.6.1.6

- name: "SCORED | 1.6.2 | Ensure SELinux is installed"
  yum:
    name: libselinux
    state: present
  when:
    - rhel7cis_rule_1_6_2
  tags:
    - rule_1.6.2

- name: "SCORED | 1.7.1.1 | Ensure message of the day is configured properly\n
         NOTSCORED | 1.7.1.4 | Ensure permissions on /etc/motd are configured"
  copy:
    content: ""
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when:
    - rhel7cis_rule_1_7_1_1
    - rhel7cis_rule_1_7_1_4
  tags:
    - rule_1.7.1.1
    - rule_1.7.1.4

- name: "NOTSCORED | 1.7.1.2 | Ensure local login warning banner is configured properly\n
         SCORED | 1.7.1.5 | Ensure permissions on /etc/issue are configured"
  template:
    src: etc/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644
  when:
    - rhel7cis_rule_1_7_1_2
    - rhel7cis_rule_1_7_1_5
  tags:
    - rule_1.7.1.2
    - rule_1.7.1.5

- name: "NOTSCORED | 1.7.1.3 | Ensure remote login warning banner is configured properly\n
         NOTSCORED | 1.7.1.6 | Ensure permissions on /etc/issue.net are configured"
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  when:
    - rhel7cis_rule_1_7_1_3
    - rhel7cis_rule_1_7_1_6
  tags:
    - rule_1.7.1.3
    - rule_1.7.1.6

- name: "SCORED | 1.7.2 | Ensure GDM login banner is configured"
  debug:
    msg: "Not needed as we don't install the Red Hat GUI"
  when:
    - rhel7cis_rule_1_7_2
  tags:
    - rule_1.7.2

- name: "NOTSCORED | 1.8 | Ensure updates, patches, and additional security software are installed"
  debug:
    msg: "Updates are only released on a fixed schedule base"
  when:
    - rhel7cis_rule_1_8
  tags:
    - rule_1.8
