---
- name: "NOTSCORED | 4.1.1.1 | Ensure audit log storage size is configured\n
         SCORED | 4.1.1.2 | Ensure system is disabled when audit logs are full\n
         SCORED | 4.1.1.3 | Ensure audit logs are not automatically deleted"
  template:
    src: etc/audit/auditd.conf
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: 0640
    backup: yes
  when:
    - rhel7cis_rule_4_1_1_1
    - rhel7cis_rule_4_1_1_2
    - rhel7cis_rule_4_1_1_3
  notify: restart auditd
  tags:
    - rule_4.1.1.1
    - rule_4.1.1.2
    - rule_4.1.1.3

- name: "SCORED | 4.1.2 | Ensure auditd service is enabled"
  systemd:
    name: auditd
    state: started
    enabled: yes
  when:
    - rhel7cis_rule_4_1_2
  tags:
    - rule_4.1.2

- name: "SCORED | 4.1.3 | Ensure auditing for processes that start prior to auditd is enabled"
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX\s*\=\s*(?!.*audit)\"[^\"]+)(\".*)'
    line: '\1 audit=1\2'
    backup: yes
  notify: generate new grub config
  when:
    - rhel7cis_rule_4_1_3
  tags:
    - rule_4.1.3

- name: "SCORED | 4.1.4 | Ensure events that modify date and time information are collected\n
         SCORED | 4.1.5 | Ensure events that modify user/group information are collected\n
         SCORED | 4.1.6 | Ensure events that modify the system's network environment are collected\n
         SCORED | 4.1.7 | Ensure events that modify the system's Mandatory Access Controls are collected\n
         SCORED | 4.1.8 | Ensure login and logout events are collected\n
         SCORED | 4.1.9 | Ensure session initiation information is collected\n
         SCORED | 4.1.10 | Ensure discretionary access control permission modification events are collected\n
         SCORED | 4.1.11 | Ensure unsuccessful unauthorized file access attempts are collected\n
         SCORED | 4.1.13 | Ensure successful file system mounts are collected\n
         SCORED | 4.1.14 | Ensure file deletion events by users are collected\n
         SCORED | 4.1.15 | Ensure changes to system administration scope (sudoers) is collected\n
         SCORED | 4.1.16 | Ensure system administrator actions (sudolog) are collected\n
         SCORED | 4.1.17 | Ensure kernel module loading and unloading is collected\n
         SCORED | 4.1.18 | Ensure the audit configuration is immutable"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - etc/audit/rules.d/rhel7cis_rule_4_1_4.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_5.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_6.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_7.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_8.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_9.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_10.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_11.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_13.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_14.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_15.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_16.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_17.rules
    - etc/audit/rules.d/rhel7cis_rule_4_1_18.rules
  when:
    - rhel7cis_rule_4_1_4
    - rhel7cis_rule_4_1_5
    - rhel7cis_rule_4_1_6
    - rhel7cis_rule_4_1_7
    - rhel7cis_rule_4_1_8
    - rhel7cis_rule_4_1_9
    - rhel7cis_rule_4_1_10
    - rhel7cis_rule_4_1_11
    - rhel7cis_rule_4_1_13
    - rhel7cis_rule_4_1_14
    - rhel7cis_rule_4_1_15
    - rhel7cis_rule_4_1_16
    - rhel7cis_rule_4_1_17
    - rhel7cis_rule_4_1_18
  notify:
    - restart auditd
  tags:
    - rule_4.1.4
    - rule_4.1.5
    - rule_4.1.6
    - rule_4.1.7
    - rule_4.1.8
    - rule_4.1.9
    - rule_4.1.10
    - rule_4.1.11
    - rule_4.1.13
    - rule_4.1.14
    - rule_4.1.15
    - rule_4.1.16
    - rule_4.1.17
    - rule_4.1.18

- block:
    - name: "SCORED | 4.1.12 | Ensure use of privileged commands is collected"
      shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
      register: priv_procs
      changed_when: no
      check_mode: no

    - name: "SCORED | 4.1.12 | Ensure use of privileged commands is collected"
      template:
        src: etc/audit/rules.d/rhel7cis_rule_4_1_12.rules.j2
        dest: /etc/audit/rules.d/rhel7cis_rule_4_1_12.rules
        owner: root
        group: root
        mode: 0600
      notify: restart auditd
  when:
    - rhel7cis_rule_4_1_12
  tags:
    - rule_4.1.12

- name: "SCORED | 4.2.1.1 | Ensure rsyslog Service is enabled"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_1
  tags:
    - rule_4.2.1.1

- name: "NOTSCORED | 4.2.1.2 | Ensure logging is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_2
  tags:
    - rule_4.2.1.2

- name: "SCORED | 4.2.1.3 | Ensure rsyslog default file permissions configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_3
  tags:
    - rule_4.2.1.3

- name: "SCORED | 4.2.1.4 | Ensure rsyslog is configured to send logs to a remote log host"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_4
  tags:
    - rule_4.2.1.4

- name: "NOTSCORED | 4.2.1.5 | Ensure remote rsyslog messages are only accepted on designated log hosts."
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_5
  tags:
    - rule_4.2.1.5

- name: "NOTSCORED | 4.2.1.5 | Ensure remote rsyslog messages are only accepted on designated log hosts."
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_1_5
  tags:
    - rule_4.2.1.5

- name: "SCORED | 4.2.2.1 | Ensure syslog-ng service is enabled"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_2_1
  tags:
    - rule_4.2.2.1

- name: "NOTSCORED | 4.2.2.2 | Ensure logging is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_2_2
  tags:
    - rule_4.2.2.2

- name: "SCORED | 4.2.2.3 | Ensure syslog-ng default file permissions configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_2_3
  tags:
    - rule_4.2.2.3

- name: "NOTSCORED | 4.2.2.4 | Ensure syslog-ng is configured to send logs to a remote log host"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_2_4
  tags:
    - rule_4.2.2.4

- name: "NOTSCORED | 4.2.2.5 | Ensure remote syslog-ng messages are only accepted on designated log hosts"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_rule_4_2_2_5
  tags:
    - rule_4.2.2.5

- name: "SCORED | 4.2.4 | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: no
  failed_when: no
  when:
    - rhel7cis_rule_4_2_4
  tags:
    - rule_4.2.4

- name: "NOTSCORED | 4.3 | Ensure logrotate is configured"
  debug:
    msg: "There is no specific logrotate schedule required"
  tags:
    - rule_4.3
